//This file has been generated by DLL_Wrapper
#pragma once

#pragma comment(linker, "/export:ord4=Target_DLL2.dll.#4,@4,NONAME")
#pragma comment(linker, "/export:print_dll_name=Target_DLL2.dll.print_dll_name,@2")
#pragma comment(linker, "/export:ord5=Target_Ordinal_ForwardTo.#1,@5,NONAME")
#pragma comment(linker, "/export:ord7=Target_Ordinal_ForwardTo.named_forward_test,@7,NONAME")
#pragma comment(linker, "/export:ordinal_forward_test=Target_Ordinal_ForwardTo.#1,@6")
#pragma comment(linker, "/export:named_forward_test=Target_Ordinal_ForwardTo.named_forward_test,@8")
