/*
** Header generated by DLL_Wrapper.
**
** This file contains function declerations for each intercepted DLL function.
**
*/
#pragma once
#include <stdio.h>
#include <Windows.h>
#include "forwards.h"

#define	INTERCEPTED_API __declspec(dllexport)

extern "C" void		*(c_ext_intercepts[2]);



// Uncomment line bellow if NOT using the .DEF file.
// DEF file needed to export with specific ordinal value.
//extern "C" INTERCEPTED_API int		print_hello();
extern "C" int						print_hello_bridge();



// Uncomment line bellow if NOT using the .DEF file.
// DEF file needed to export with specific ordinal value.
//extern "C" INTERCEPTED_API int		add_numbers(int a, int b);
extern "C" int						add_numbers_bridge(int a, int b);

